{% set version = "2.4-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatstat.core
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatstat.core_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatstat.core/spatstat.core_{{ version }}.tar.gz
  sha256: e38c39efe8b14d6e8fdbee8dd870b90c52f78ea571ab7988fd3685f48347d13b

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rpart                    # [build_platform != target_platform]
    - r-spatstat.geom            # [build_platform != target_platform]
    - r-abind                    # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-spatstat.data            # [build_platform != target_platform]
    - r-spatstat.random          # [build_platform != target_platform]
    - r-mgcv                     # [build_platform != target_platform]
    - r-nlme                     # [build_platform != target_platform]
    - r-spatstat.utils           # [build_platform != target_platform]
    - r-tensor                   # [build_platform != target_platform]
    - r-spatstat.sparse          # [build_platform != target_platform]
    - r-goftest                  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-abind
    - r-goftest >=1.2_2
    - r-mgcv
    - r-nlme
    - r-rpart
    - r-spatstat.data >=2.1_0
    - r-spatstat.geom >=2.3_0
    - r-spatstat.random >=2.0
    - r-spatstat.sparse >=2.0_0
    - r-spatstat.utils >=2.2_0
    - r-tensor
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-abind
    - r-goftest >=1.2_2
    - r-mgcv
    - r-nlme
    - r-rpart
    - r-spatstat.data >=2.1_0
    - r-spatstat.geom >=2.3_0
    - r-spatstat.random >=2.0
    - r-spatstat.sparse >=2.0_0
    - r-spatstat.utils >=2.2_0
    - r-tensor

test:
  commands:
    - $R -e "library('spatstat.core')"           # [not win]
    - "\"%R%\" -e \"library('spatstat.core')\""  # [win]

about:
  home: http://spatstat.org/
  license: GPL-2.0-or-later
  summary: This is a subset of the original 'spatstat' package, containing all of the user-level code from 'spatstat', except for the code for linear networks.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: spatstat.core
# Version: 1.65-5
# Date: 2021-02-01
# Title: Core Functionality of the 'spatstat' Package
# Authors@R: c(person("Adrian", "Baddeley", role = c("aut", "cre"), email = "Adrian.Baddeley@curtin.edu.au"), person("Rolf", "Turner", role = "aut", email="r.turner@auckland.ac.nz"), person("Ege",   "Rubak", role = "aut", email = "rubak@math.aau.dk"), person("Kasper", "Klitgaard Berthelsen", role = "ctb"), person("Ottmar", "Cronie", role = "ctb"), person("Tilman", "Davies", role = "ctb"), person("Julian", "Gilbey", role = "ctb"), person("Yongtao", "Guan", role = "ctb"), person("Ute", "Hahn", role = "ctb"), person("Kassel", "Hingee", role = "ctb"), person("Abdollah", "Jalilian", role = "ctb"), person("Marie-Colette", "van Lieshout", role = "ctb"), person("Greg", "McSwiggan", role = "ctb"), person("Tuomas", "Rajala", role = "ctb"), person("Suman", "Rakshit", role = "ctb"), person("Dominic", "Schuhmacher", role = "ctb"), person("Rasmus", "Plenge Waagepetersen", role = "ctb"), person("Hangsheng", "Wang", role = "ctb"))
# Maintainer: Adrian Baddeley <Adrian.Baddeley@curtin.edu.au>
# Depends: R (>= 3.5.0), spatstat.data (>= 1.6-1), spatstat.geom, stats, graphics, grDevices, utils, methods, nlme, rpart
# Imports: spatstat.utils (>= 1.18-0), spatstat.sparse, mgcv, Matrix, abind, tensor, goftest (>= 1.2-2)
# Suggests: sm, maptools (>= 0.9-9), gsl, locfit, spatial, RandomFields (>= 3.1.24.1), RandomFieldsUtils(>= 0.3.3.1), fftwtools (>= 0.9-8), spatstat.linnet
# Description: This is a subset of the original 'spatstat' package, containing all of the user-level code from 'spatstat', except for the code for linear networks.
# License: GPL (>= 2)
# URL: http://spatstat.org/
# LazyData: true
# NeedsCompilation: yes
# ByteCompile: true
# BugReports: https://github.com/spatstat/spatstat.core/issues
# Packaged: 2021-02-01 00:45:25 UTC; adrian
# Author: Adrian Baddeley [aut, cre], Rolf Turner [aut], Ege Rubak [aut], Kasper Klitgaard Berthelsen [ctb], Ottmar Cronie [ctb], Tilman Davies [ctb], Julian Gilbey [ctb], Yongtao Guan [ctb], Ute Hahn [ctb], Kassel Hingee [ctb], Abdollah Jalilian [ctb], Marie-Colette van Lieshout [ctb], Greg McSwiggan [ctb], Tuomas Rajala [ctb], Suman Rakshit [ctb], Dominic Schuhmacher [ctb], Rasmus Plenge Waagepetersen [ctb], Hangsheng Wang [ctb]
# Repository: CRAN
# Date/Publication: 2021-02-01 17:20:11 UTC
